name: Server CI/CD Pipeline
on:
  push:
    branches: [master]
    paths:
      - "server/**"
jobs:
  build-and-deploy:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: longvt.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Server
        run: |
          docker build -t longvt.azurecr.io/server:${{ github.sha }} ./server
          docker push longvt.azurecr.io/server:${{ github.sha }}

      - name: Update Server Container
        run: |
          az containerapp up \
            --name blossomy-server \
            --image longvt.azurecr.io/server:${{ github.sha }} \
            --ingress external \
            --location southeastasia \
            --registry-server longvt.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --target-port 5000
